config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, :controllers => { :registrations => "my_registrations" }
  resources :users
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#index'
  get 'simple_pages/landing_page'
  post 'simple_pages/thank_you'
  post 'payments/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>appy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <% if notice %>
    <div class="alert alert-primary" role="notice">
       <%= notice %>
    </div>
    <% end %>

    <% if alert %>
    <div class="alert alert-primary" role="alert">
       <%= alert %>
    </div>
    <% end %>


    <nav>
      <ul class="nav nav-tabs">
        <li role="presentation" class="active home"><%= link_to "Home", root_path %></li>
        <li role="presentation" class="about"><%= link_to "About", simple_pages_about_path %></li>
        <li role="presentation" class="contact"><%= link_to "Contact", simple_pages_contact_path %></li>
        <li role="presentation" class="products"><%= link_to "Products", products_path %></li>
        <li role="presentation" class="sale"><%= link_to "SALE", simple_pages_landing_page_path %><li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        </li>
        <% end %>
      </ul>

      <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
        <%= form.label :q, 'Search for:' %>
        <%= form.text_field :q, id: 'q', value: params[:q] %>
        <%= form.submit 'Search' %>
      <% end %>

    </nav>

  <%= yield %>

    <footer>
      <p>&copy; 2019 ZB Store </p>
    </footer>

  </body>
</html>